%YAML:1.0

#--------------------------------------------------------------------------------------------
# Camera Parameters. Adjust them!
#--------------------------------------------------------------------------------------------
camera.fx: 520.908620
camera.fy: 521.007327
camera.cx: 325.141442
camera.cy: 249.701764
camera.scale: 1.0
camera.width: 640
camera.height: 480



