%YAML:1.0

#--------------------------------------------------------------------------------------------
# Camera Parameters. Adjust them!
#--------------------------------------------------------------------------------------------
camera.fx: 535.4
camera.fy: 539.2
camera.cx: 320.1
camera.cy: 247.6
camera.scale: 1.0
camera.width: 640
camera.height: 480
